# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh from templates/to11.rb.tmpl.
# Do not edit this file — edit the template.

class To11 < Formula
  desc "Agent skill sharing for your whole team"
  homepage "https://github.com/to11ai/to11-cli"
  license :cannot_represent

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.5.1/to11_0.5.1_darwin_arm64.tar.gz"
      sha256 "16c347d3ffe0045e522b6743ab0c142c0edc2a5c8edb5d9be759a895b4ea8c08"
    end
    on_intel do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.5.1/to11_0.5.1_darwin_amd64.tar.gz"
      sha256 "0fac5131c18ca6a9ed887782f6594192f39a5a3384c891ad5b7e7e477037a664"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.5.1/to11_0.5.1_linux_arm64.tar.gz"
      sha256 "90744402fc849feb383d186d3a49c02479168ada5ecc66c3d8bad1ccdd894f45"
    end
    on_intel do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.5.1/to11_0.5.1_linux_amd64.tar.gz"
      sha256 "e865210dc0f8950c2993e167daa346a65692040f10c55c0babf91aaa770d5fe9"
    end
  end

  def install
    bin.install "to11"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/to11 --version")
  end
end
