# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh from templates/to11.rb.tmpl.
# Do not edit this file — edit the template.

class To11 < Formula
  desc "Agent skill sharing for your whole team"
  homepage "https://github.com/to11ai/to11-cli"
  license :cannot_represent

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.10.0/to11_0.10.0_darwin_arm64.tar.gz"
      sha256 "9d3d59c61d3ce4f010a7e3852e885fe5a8019c122367c87010d88589b211a5d0"
    end
    on_intel do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.10.0/to11_0.10.0_darwin_amd64.tar.gz"
      sha256 "ab0a23d1165d47614a11567faa1dfec5676e07c1dfad61cbe10268fbde8c8531"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.10.0/to11_0.10.0_linux_arm64.tar.gz"
      sha256 "35cc4ea77a4b096205a71c37bfe9aee8a2bb9e6fbb6bd790b96ca9450b7e1d95"
    end
    on_intel do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.10.0/to11_0.10.0_linux_amd64.tar.gz"
      sha256 "12f807e18822077909d1f736ed3e3ef5eb1be4d410085321cfd0e040e85ab893"
    end
  end

  def install
    bin.install "to11"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/to11 --version")
  end
end
