# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh from templates/to11.rb.tmpl.
# Do not edit this file — edit the template.

class To11 < Formula
  desc "Agent skill sharing for your whole team"
  homepage "https://github.com/to11ai/to11-cli"
  license :cannot_represent

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.12.0/to11_0.12.0_darwin_arm64.tar.gz"
      sha256 "a61c639e977317632a1d760be1527e771a5e30e193ba355b7654c97a224ec3c0"
    end
    on_intel do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.12.0/to11_0.12.0_darwin_amd64.tar.gz"
      sha256 "347754440d85404f0f7509f0b29b52252d9e99e7c1b6cad260eea18d9e4e9f36"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.12.0/to11_0.12.0_linux_arm64.tar.gz"
      sha256 "a243229e3aea7cacf14f748a92d3649ad0486534e2d32ba092590ae527bdea85"
    end
    on_intel do
      url "https://github.com/to11ai/to11-cli/releases/download/v0.12.0/to11_0.12.0_linux_amd64.tar.gz"
      sha256 "df8c5e41402cff36d589f9b8deeeb7d03cd10e672d874bf98ee9f1a43c741d3f"
    end
  end

  def install
    bin.install "to11"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/to11 --version")
  end
end
